repos:
  # Strip outputs from Jupyter notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  # Auto-format with black
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
