[tool.poetry]
name = "herbarium-processor"
version = "0.1.0"
description = "Tools for processing herbarium specimen labels"
readme = "README.md"
authors = ["Liann Sun <lisunshiny@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10"
ipython = "*"
google-generativeai = "*"
python-dotenv = "*"
pandas = "*"
requests = "*"
beautifulsoup4 = "*"
matplotlib = "*"
seaborn = "*"
pytesseract = "*"
pillow-heif = "*"
google-cloud-vision = "*"
opencv-python = "*"
jinja2 = "*"
google_cloud_vision = "*"
fastapi = "*"
uvicorn = "*"
python-multipart = "*"
pyyaml = "*"
openai = "^1.102.0"

[tool.poetry.group.dev.dependencies]
pytest = "*"
ipykernel = "^6.29.5"
nbstripout = "^0.8.1"
pre-commit = "^4.3.0"
black = {extras = ["jupyter"], version = "^25.1.0"}
httpx = "*"

[tool.poetry.scripts]
dev = "scripts.dev:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
