csv_path: data/cs_canonical.csv
field_list:
  - label_header
  - scientific_name
  - field_collection_location_verbatim
  - county
  - state
  - country
  - verbatim_latitude
  - verbatim_longitude
  - elevation
  - habitat_information
  - field_collection_date
  - comment
  - field_collectors
  - field_collection_number
  - identifier
  - identification_date
  - exsiccatae
  - associated_taxa
  - old_identifier
  - old_identification_date
shot_data:
  - id: UC46732_2
    img_path: prompts/few_shot_data/UC46732_2.JPG
    ocr_path: prompts/few_shot_data/ocr_ai_input_UC46732_2.json
  - id: UC1207518_2
    img_path: prompts/few_shot_data/UC1207518_2.JPG
    ocr_path: prompts/few_shot_data/ocr_ai_input_UC1207518_2.json
  - id: UC1318628_2
    img_path: prompts/few_shot_data/UC1318628_2.JPG
    ocr_path: prompts/few_shot_data/ocr_ai_input_UC1318628_2.json
template_path: prompts/templates/herbarium_prompt.j2
