csv_path: data/csv/fake_canonical.csv
field_list:
  - taxon
  - locality
  - coordinates
  - date
  - elevation
  - id
  - substrate
shot_data: []
template_path: prompts/templates/herbarium_prompt.j2
